font-family = "VictorMono Nerd Font Propo"
font-size = 13.5
adjust-cell-height = 35%


maximize = true
alpha-blending = native

working-directory = home
shell-integration = fish
shell-integration-features = no-cursor
cursor-style = block
adjust-cursor-height = 25%
window-theme = system
window-decoration = auto
window-padding-x = 1
window-padding-y = 1
window-padding-balance = true
window-height=510
window-width=1640
theme = dark:TokyoNight,light:TokyoNight Day
