font-family = "VictorMono Nerd Font Propo"
font-size = 14

window-padding-x = 0
window-padding-y = 0
window-decorations = true
window-width = 220
window-height = 50

cursor-style = block
cursor-style-blink = true
cursor-opacity = 1.0

text-blink-rate = 500
line-height = 1.25

tabs-location = top
tabs-max-width = 16

keybind = cmd+p=send-keys:ctrl+p
keybind = cmd+n=send-keys:ctrl+n
keybind = alt+left=send-keys:alt+b
keybind = alt+right=send-keys:alt+f

status-right = battery:"🔋 {percentage}%"
status-right = date:"%a %b %-d %H:%M:%S " 