-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- wrap and check for spell in text filetypes
-- vim.api.nvim_create_autocmd("BufNewFile,BufRead", {
--   group = augroup("wrap_spell"),
--   pattern = { "*.config" },
--   callback = function()
--     filetype = "yaml"
--   end,
-- })
